/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import coldware.ConexionBD;
import coldware.Planeta;
import coldware.Planeta;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author DAW2
 */
public class ResumenRonda extends javax.swing.JDialog {
    
 private int jugador = 0;
    private List<Planeta> planetas;
    /**
     * Creates new form ResumenRonda
     */
    public ResumenRonda(ArrayList <String> movimientos,List<Planeta> planetas) {
        initComponents();
          this.setResizable(false);
          
           
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

       
         this.setBounds((ancho/2) - (this.getWidth()/2 ), (alto/2 ) - (this.getHeight()/2 ), 1015, 550);
          cursores();
          jTextArea1.setOpaque(true);
         jTextArea1.setBackground(new Color(0,0,0,0));
         jTextArea1.setBorder(null);
         jScrollPane1.setBorder(null);
          jTextArea2.setOpaque(true);
         jTextArea2.setBackground(new Color(0,0,0,0));
         jTextArea2.setBorder(null);
          jScrollPane2.setBorder(null);
          
           
        String stringMovimientos="";
         String stringVidas="";
         setimagenes();
         this.setModal(true);
             Font fuente = new Font("Calibri", 3, 13);
             Font fuente1 = new Font("Calibri", 3, 14);
            jTextArea1.setFont(fuente);
            jTextArea2.setFont(fuente1);
   
        for (int i = 0; i < movimientos.size(); i++) {
            
            stringMovimientos=stringMovimientos+movimientos.get(i)+"\n";
             jTextArea1.setText(stringMovimientos);
             
             
        }
        for (int i = 0; i < planetas.size(); i++) {
           
            stringVidas=stringVidas+planetas.get(i).getNombre()+" tiene "+planetas.get(i).getVidas()+" vidas\n";
             jTextArea2.setText(stringVidas);
            
            
        }
    
           
        System.out.println("EL VIEJO SAAANCAAAAAAA");
        System.out.println(planetas);
        
        this.planetas=planetas;
             
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 860, 180));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 270, 160));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 190));

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 323, 150, 40));

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 150, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
           String[] botones = {"Guardar y salir", "Guardar y continuar", "Cancelar"};
       int ventana = JOptionPane.showOptionDialog(null, "Pulsa un boton:", "Javadesde0.com", JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE, null,botones, botones[0]);
        String Resultado="";	
       if(ventana == 0) {
            Resultado="Guardado correctamente, se va a cerrar el juego...";
          JOptionPane.showMessageDialog(null, Resultado);
          ConexionBD.addPlanetas(planetas);
          System.exit(0);
       } 			
       else if(ventana == 1) {
           Resultado="Guardado correctamente, continuemos la batalla";	
            JOptionPane.showMessageDialog(null, Resultado);
            ConexionBD.addPlanetas(planetas);
       }
       else if(ventana == 2) {
           Resultado="Después no nos vengas llorando que no encuentras tus datos";	
            JOptionPane.showMessageDialog(null, Resultado);
       }
 
    
        System.out.println(planetas);
        //ConexionBD.crearBD();
        //ConexionBD.addPlanetas(planetas);
    }//GEN-LAST:event_jButton2ActionPerformed

  
           void cursores(){
        
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    }
 
    void setimagenes(){
		  jLabel1.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\fondoresumenronda.jpg")); // NOI18N
		
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
